-- Staging table for NH Provider Info.
-- Truncated before each COPY; no DISTKEY/SORTKEY needed (small, ephemeral).
-- Column list must match the COPY column list in the Step Function exactly.
-- No snapshot_date_key or lineage columns here — those are added when the
-- data is loaded into silver, not part of the raw file itself.

CREATE TABLE IF NOT EXISTS staging.nh_provider_info_stg (

    provnum                             VARCHAR(20),
    provider_name                       VARCHAR(255),
    provider_address                    VARCHAR(255),
    city                                VARCHAR(100),
    state                               VARCHAR(2),
    zip_code                            INTEGER,
    telephone_number                    BIGINT,
    ssa_county_code                     SMALLINT,
    county_name                         VARCHAR(100),
    ownership_type                      VARCHAR(100),
    certified_beds                      SMALLINT,
    avg_residents_per_day               DECIMAL(4,1),
    avg_residents_per_day_footnote      SMALLINT,
    provider_type                       VARCHAR(100),
    resides_in_hospital                 BOOLEAN,
    legal_business_name                 VARCHAR(255),
    date_first_approved                 DATE,
    affiliated_entity_name              VARCHAR(255),
    affiliated_entity_id                SMALLINT,
    ccrc_status                         BOOLEAN,
    special_focus_status                VARCHAR(50),
    abuse_icon                          BOOLEAN,
    health_inspection_over_2yrs         BOOLEAN,
    ownership_change_last_12mo          BOOLEAN,
    resident_family_council             VARCHAR(10),
    sprinkler_systems_all_areas         VARCHAR(10),

    overall_rating                      SMALLINT,
    overall_rating_footnote             SMALLINT,
    health_inspection_rating            SMALLINT,
    health_inspection_rating_footnote   SMALLINT,
    qm_rating                           SMALLINT,
    qm_rating_footnote                  SMALLINT,
    longstay_qm_rating                  SMALLINT,
    longstay_qm_rating_footnote         SMALLINT,
    shortstay_qm_rating                 SMALLINT,
    shortstay_qm_rating_footnote        SMALLINT,
    staffing_rating                     SMALLINT,
    staffing_rating_footnote            SMALLINT,

    reported_staffing_footnote          SMALLINT,
    pt_staffing_footnote                SMALLINT,
    reported_cna_hprd                   DECIMAL(6,5),
    reported_lpn_hprd                   DECIMAL(6,5),
    reported_rn_hprd                    DECIMAL(6,5),
    reported_licensed_hprd              DECIMAL(6,5),
    reported_total_nurse_hprd           DECIMAL(7,5),
    reported_weekend_total_nurse_hprd   DECIMAL(7,5),
    reported_weekend_rn_hprd            DECIMAL(6,5),
    reported_pt_hprd                    DECIMAL(6,5),

    total_nurse_turnover_pct            DECIMAL(4,1),
    total_nurse_turnover_footnote       SMALLINT,
    rn_turnover_pct                     DECIMAL(4,1),
    rn_turnover_footnote                SMALLINT,
    administrators_left_count           SMALLINT,
    administrator_turnover_footnote     SMALLINT,

    nursing_case_mix_index              DECIMAL(6,5),
    nursing_case_mix_index_ratio        DECIMAL(6,5),
    casemix_cna_hprd                    DECIMAL(6,5),
    casemix_lpn_hprd                    DECIMAL(6,5),
    casemix_rn_hprd                     DECIMAL(6,5),
    casemix_total_nurse_hprd            DECIMAL(7,5),
    casemix_weekend_total_nurse_hprd    DECIMAL(6,5),
    adjusted_cna_hprd                   DECIMAL(6,5),
    adjusted_lpn_hprd                   DECIMAL(6,5),
    adjusted_rn_hprd                    DECIMAL(6,5),
    adjusted_total_nurse_hprd           DECIMAL(7,5),
    adjusted_weekend_total_nurse_hprd   DECIMAL(7,5),

    cycle1_survey_date                       DATE,
    cycle1_total_health_deficiencies         SMALLINT,
    cycle1_standard_health_deficiencies      SMALLINT,
    cycle1_complaint_health_deficiencies     SMALLINT,
    cycle1_health_deficiency_score           SMALLINT,
    cycle1_health_revisits                   SMALLINT,
    cycle1_health_revisit_score              SMALLINT,
    cycle1_total_health_score                SMALLINT,

    cycle2_survey_date                       DATE,
    cycle2_total_health_deficiencies         SMALLINT,
    cycle2_standard_health_deficiencies      SMALLINT,
    cycle2_complaint_health_deficiencies     SMALLINT,
    cycle2_health_deficiency_score           SMALLINT,
    cycle2_health_revisits                   SMALLINT,
    cycle2_health_revisit_score              SMALLINT,
    cycle2_total_health_score                SMALLINT,

    cycle3_survey_date                       DATE,
    cycle3_total_health_deficiencies         SMALLINT,
    cycle3_standard_health_deficiencies      SMALLINT,
    cycle3_complaint_health_deficiencies     SMALLINT,
    cycle3_health_deficiency_score           SMALLINT,
    cycle3_health_revisits                   SMALLINT,
    cycle3_health_revisit_score              SMALLINT,
    cycle3_total_health_score                SMALLINT,

    total_weighted_health_score         DECIMAL(7,3),
    facility_reported_incidents         SMALLINT,
    substantiated_complaints            SMALLINT,
    infection_control_citations         SMALLINT,
    num_fines                           SMALLINT,
    total_fines_amount                  DECIMAL(9,2),
    payment_denials                     SMALLINT,
    total_penalties                     SMALLINT,
    location                            VARCHAR(500),
    latitude                             DECIMAL(6,4),
    longitude                            DECIMAL(6,3),
    geocoding_footnote                  SMALLINT,
    processing_date                     DATE

)
DISTSTYLE EVEN;
